Scorpio "AshToAsh.BlizzardSkin.Localization.enUS" ""

local L = _Locale("enUS", true)

L["menu_title"] = "Blizzard Skin"
L["tips"] = "Tips"
L["appearance"] = "Appearance"

L["visibility"] = "Visibility"
L["visibility_hide"] = "Hide"
L["visibility_show_only_party"] = "Show only in party"
L["visibility_show_always"] = "Show always"
L["visibility_show"] = "Show"

L["cast_bar"] = "Cast bar"
L["power_bar"] = "Power bar"
L["health_bar"] = "Health bar"
L["power_bar_visibility_tips"] = "Hiding the power bar will also hide the casting bar!"
L["health_text_format"] = "Health format"
L["health_text_format_normal"] = "Normal"
L["health_text_format_kilo"] = "xx.xK"
L["health_text_format_ten_thousand"] = "xx.xW(China Only)"
L["name_format"] = "Name format"
L["name_format_noserver"] = "Only display the player's name"
L["name_format_server_shorthand"] = "Replace server with (*)"
L["name_format_withserver"] = "Display server"
L["friends_name_coloring"] = "Friends name coloring"
L["guild_friend_color"] = "Guild friend"
L["battle_net_friend_color"] = "BN friend"
L["friend_color"] = "Friend"