Scorpio "AshToAsh.BlizzardSkin.Localization.enUS" ""

local L = _Locale("enUS", true)

L["menu_title"] = "Blizzard Skin"
L["default"] = "Default"
L["panel_mask_tips"] = "Only if the index of the panel is greater than that of the other panel, it will be automatically attached!"
L["panel_moving_tips"] = "Hold down the Alt key to move the panel"
L["tips"] = "Tips"
L["appearance"] = "Appearance"
L["block_blizzard_unitframe"] = "Block Blizzard CompactUnitFrame"
L["block_blizzard_unitframe_tips"] = "Anyway, it’s always no good to run ATA and the Blizzard CompactUnitFrame at the same time, right?\nTurning on/off this option will reload ui"

L["adjust_auto_attach_margin"] = "Adjust panel(%d)'s margin"
L["adjust_auto_attach_margin_tips"] = "When panel is auto attched, you cat set it's margin use this option."
L["adjust_auto_attach_margin_input_title"] = "Input margin(-100~100)"
L["adjust_all_elements"] = "|cff7CFC00Element Settings|r"
L["adjust_all_elements_tips"] = "Set all elements of the same type of panel"
L["adjust_all_elements_width"] = "Element Width"
L["adjust_all_elements_height"] = "Element Height"

L["visibility"] = "Visibility"
L["visibility_hide"] = "Hide"
L["visibility_show_only_party"] = "Show only in party"
L["visibility_show_always"] = "Show always"
L["visibility_show"] = "Show"

L["texture"] = "Texture"
L["background_texture"] = "Background texture"
L["unitframe_background"] = "Unitframe background"

L["font"] = "Font"
L["font_outline"] = "Outline"
L["font_outline_none"] = "None"
L["font_outline_normal"] = "Normal"
L["font_outline_thick"] = "Thick"
L["font_size"] = "Size"
L["font_monochrome"] = "Monochrome"

L["aura"] = "Aura"
L["aura_size"] = "Aura Size"
L["aura_size_tips"] = "Adjust the basic size of the aura, which only affects the Buff and Debuff, and the class buff, enlarge debuff, etc. are not affected.\n|cffffffff The aura will still scale with the frame|r"
L["aura_disable_tooltip"] = "Disable tooltip"
L["aura_disable_tooltip_tips"] = "Disabling game tooltip allows you to hover over the aura to click and cast spells."
L["aura_show_countdown_numbers_tips"] = "Enabling this option just means that you follow the Blizzard settings, if you are not using OmniCC, you still need to turn on thein the \"".. COUNTDOWN_FOR_COOLDOWNS_TEXT .. "\" option.\n\n|cffff0000 If the aura frame is too small, OmniCC will not display countdown number.\nYou'll need to adjust the aura size or adjust OmniCC's \"Minimum Cooldown Size\" option to achieve the desired effect, usually the latter is more useful|r"
L["aura_quick_block_tips"] = "|cffffffffAlt + Right mouse click to add aura to \"Black list\"|r"
L["aura_quick_enlarge_debuff_tips"] = "|cff7CFC00Ctrl + Left mouse click to add debuff to \"Enlarge debuff list\"|r"

L["cast_bar"] = "Cast bar"
L["power_bar"] = "Power bar"
L["health_bar"] = "Health bar"
L["power_bar_visibility_tips"] = "Hiding the power bar will also hide the casting bar!"
L["health_text_format"] = "Health format"
L["health_text_format_normal"] = "Normal"
L["health_text_format_kilo"] = "xx.xK"
L["health_text_format_ten_thousand"] = "xx.xW(China Only)"
L["health_text_scale_with_frame"] = "Health scale with frame"
L["name_format"] = "Name format"
L["name_format_noserver"] = "Only display the player's name"
L["name_format_server_shorthand"] = "Replace server with (*)"
L["name_format_withserver"] = "Display server"
L["name_scales_with_frame"] = "Scale with frame"
L["guild_friend_color"] = "Guild friend"
L["battle_net_friend_color"] = "BN friend"
L["friend_color"] = "Friend"
L["nick_name"] = "Nickname"
L["nick_name_format"] = "Nickname:%s"
L["nick_name_setting"] = "Set nickname"
L["show_nick_name_owns"] = "Show one's own nickname"
L["show_nick_name_to_others"] = "Show my nickname to others"
L["show_nick_name_others"] = "Show others' nicknames"
L["show_nick_name_to_others_tips"] = "After checking this option, others will see your nickname"
L["err_nickname_too_long"] = "Nickname is too long"
L["show_panel_label"] = "Display unit panel label"
L["show_pet_panel_label"] = "Display pet panel label"
L["show_panel_label_tips"] = "When only one item is checked in any group filter, the panel label will be displayed, such as: Group N"
L["show_focus_indicator"] = "Display focus highlight"
L["show_dispellable_debuff_indicator"] = "Display dispellabel debuff highlight"
L["show_dispellable_debuff_indicator_tips"] = "If the unit has a Debuff that you can dispell, the unit frame will be highlighted"

L["template"] = "Template"
L["template_tips"] = "You can save the current AshToAsh and Blizzard skin configuration as a template, and the template is account-common. When needed, you can apply a template with one click. \n|cffffffff In the retail, the configuration of the ATA and Blizzard skins is switched with specialization, and in the classic, it is switched with the role.\nThe template does not contain the aura watch list, because they are account-common already.|r\n\nNote: The template just copies its configuration to the current character or specialization (determined by your World of Warcraft version), updating the template will not update the configuration based on the template."
L["err_add_template"] = "The template name cannot be empty or there is already a template with the same name"
L["template_apply"] = "Apply template"
L["template_apply_confirm"] = "Confirm apply template: |cff00ff00%s|r"
L["template_update"] = "Update template"
L["template_update_tips"] = "Update the currently used configuration to this template"
L["template_update_confirm"] = "Confirm update template: |cff00ff00%s|r"
L["template_delete"] = "Delete template"
L["template_delete_confirm"] = "Confirm delete template: |cffff0000%s|r"
L["template_apply_tips"] = "Click this option will reload ui.\n|cffff0000 Please note: With the update of the addon, apply the old version of the template may cause the configuration to be damaged. At that time, you may need to delete the template that caused the error and the AshToAsh.lua in the WTF of the corresponding role. |r"
L["template_default_apply"] = "Apply default template"
L["template_default_apply_tips"] = "Click this option will apply the default template: 8 vertical party panels"
L["template_default_apply_confirm"] = "Confirm apply default template ?"

L["feared"] = "Feared"
L["charmed"] = "Charmed"
L["stunned"] = "Stunned"
L["banished"] = "Banished"
L["silenced"] = "Silenced"
L["disoriented"] = "Disoriented"
L["incapacitated"] = "Incapacitated"
L["frozen"] = "Frozen"
L["asleep"] = "Asleep"
L["disarmed"] = "Disarmed"
L["pacified"] = "Pacified"
L["shackled"] = "Shackled"
L["sapped"] = "Sapped"
L["horrified"] = "Horrified"
L["intimidated"] = "Intimidated"
L["hexed"] = "Hexed"
L["disability"] = "Disability"
L["mind_controlled"] = "Mind controlled"
L["out_of_control"] = "Out of control"