Scorpio "AshToAsh.BlizzardSkin.Localization.enUS" ""

local L = _Locale("enUS", true)

L["menu_title"] = "Blizzard Skin"
L["panel_mask_tips"] = "Only if the index of the panel is greater than that of the other panel, it will be automatically attached!"
L["tips"] = "Tips"
L["appearance"] = "Appearance"
L["block_blizzard_unitframe"] = "Block Blizzard CompactUnitFrame"
L["block_blizzard_unitframe_tips"] = "Anyway, it’s always no good to run ATA and the Blizzard CompactUnitFrame at the same time, right?\nTurning on/off this option will reload ui"

L["visibility"] = "Visibility"
L["visibility_hide"] = "Hide"
L["visibility_show_only_party"] = "Show only in party"
L["visibility_show_always"] = "Show always"
L["visibility_show"] = "Show"

L["cast_bar"] = "Cast bar"
L["power_bar"] = "Power bar"
L["health_bar"] = "Health bar"
L["power_bar_visibility_tips"] = "Hiding the power bar will also hide the casting bar!"
L["health_text_format"] = "Health format"
L["health_text_format_normal"] = "Normal"
L["health_text_format_kilo"] = "xx.xK"
L["health_text_format_ten_thousand"] = "xx.xW(China Only)"
L["health_text_scale_with_frame"] = "Health scale with frame"
L["name_format"] = "Name format"
L["name_format_noserver"] = "Only display the player's name"
L["name_format_server_shorthand"] = "Replace server with (*)"
L["name_format_withserver"] = "Display server"
L["name_scales_with_frame"] = "Scale with frame"
L["friends_name_coloring"] = "Friends name coloring"
L["guild_friend_color"] = "Guild friend"
L["battle_net_friend_color"] = "BN friend"
L["friend_color"] = "Friend"
L["nick_name"] = "Nickname"
L["nick_name_format"] = "Nickname:%s"
L["nick_name_setting"] = "Set nickname"
L["show_nick_name_owns"] = "Show one's own nickname"
L["show_nick_name_to_others"] = "Show my nickname to others"
L["show_nick_name_others"] = "Show others' nicknames"
L["show_nick_name_to_others_tips"] = "After checking this option, others will see your nickname"
L["err_nickname_too_long"] = "Nickname is too long"
L["show_panel_label"] = "Display unit panel label"
L["show_pet_panel_label"] = "Display pet panel label"
L["show_panel_label_tips"] = "When only one item is checked in any group filter, the panel label will be displayed, such as: Group N"