Scorpio "AshToAsh.BlizzardSkin.Localization.zhCN" ""

local L = _Locale("zhCN")

if not L then return end

L["menu_title"] = "暴雪皮肤"
L["tips"] = "提示"
L["appearance"] = "外观"

L["visibility"] = "可见性"
L["visibility_hide"] = "隐藏"
L["visibility_show_only_party"] = "仅小队显示"
L["visibility_show_always"] = "一直显示"
L["visibility_show"] = "显示"

L["cast_bar"] = "施法条"
L["power_bar"] = "能量条"
L["health_bar"] = "生命条"
L["power_bar_visibility_tips"] = "隐藏能量条会同时隐藏施法条！"
L["health_text_format"] = "生命值格式"
L["health_text_format_normal"] = "普通"
L["health_text_format_kilo"] = "xx.xK"
L["health_text_format_ten_thousand"] = "xx.xW"
L["name_format"] = "名字格式"
L["name_format_noserver"] = "仅显示玩家名字"
L["name_format_server_shorthand"] = "用(*)代替服务器"
L["name_format_withserver"] = "显示服务器"
L["friends_name_coloring"] = "好友名字染色"
L["guild_friend_color"] = "公会好友"
L["battle_net_friend_color"] = "战网好友"
L["friend_color"] = "好友"
L["nick_name"] = "昵称"
L["nick_name_format"] = "昵称：%s"
L["nick_name_setting"] = "设置昵称"
L["show_nick_name_owns"] = "显示自己的昵称"
L["show_nick_name_to_others"] = "对他人显示我的昵称"
L["show_nick_name_others"] = "显示他人的昵称"
L["show_nick_name_to_others_tips"] = "勾选此项后其他人会看见你的昵称"
L["err_nickname_too_long"] = "昵称过长"
L["show_panel_label"] = "显示面板标签"
L["show_panel_label_tips"] = "当任意分组过滤仅勾选一项时，显示面板标签，如：小队N"